# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
      eslint-plugins:
        patterns:
          - 'eslint-plugin-*'
          - '@*/eslint-plugin'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      stryker-mutator:
        patterns:
          - '@stryker-mutator/*'
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: npm
    directory: /examples/basic-example
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/eslint-v9
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/example-oxlint
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/example-react
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/eslint-config-internal
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/eslint-plugin-internal
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/eslint-plugin-wyrm
    schedule:
      interval: daily
