name: 🧟 Mutation testing

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

permissions:
  contents: read

env:
  CI: 1
  HUSKY: 0
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: ${{ github.ref == 'refs/heads/master' && 'pnpm' || '' }}
          # zizmor: ignore[cache-poisoning] caching restricted to trusted refs
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: 💾 Cache mutation reports
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./packages/eslint-plugin-wyrm/reports/
          key: mutation-reports-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            mutation-reports-${{ github.ref_name }}-

      - name: ⛏️ build
        run: pnpm run build
        working-directory: ./packages/eslint-plugin-wyrm/

      - name: 🧟 Run mutation testing
        run: pnpm run test:mut
        working-directory: ./packages/eslint-plugin-wyrm/
