name: 🚀 Release

on:
  push:
    branches:
      - master

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}

    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC

    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts

      - run: pnpm run build
        working-directory: ./packages/eslint-plugin-wyrm/

      - run: pnpm publish
        working-directory: ./packages/eslint-plugin-wyrm/
